CREATE TABLE category (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE avatar (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    image_url VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE secret (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    text VARCHAR(4096) NOT NULL,
    avatar_id BIGINT,
    category_id BIGINT,
    order_num INT,
    likes_count INT DEFAULT 0 NOT NULL,
    FOREIGN KEY (avatar_id) REFERENCES avatar(id),
    FOREIGN KEY (category_id) REFERENCES category(id)
);




