# import requests

# # Define the endpoint URL
# endpoint_url = 'http://192.168.1.211:8081/api/options'


# # List of request payloads
# requests_payload = [
#     {
#         "optionCode": "20DIS",
#         "shortDesc": "20% DISC",
#         "longDesc": "20% Disc Car Coverage",
#         "typeFlag": "N",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "30DIS",
#         "shortDesc": "30% DISC",
#         "longDesc": "30% Disc Car Coverage",
#         "typeFlag": "N",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "ACCTF",
#         "shortDesc": "AccsrTheft",
#         "longDesc": "Robo de Autopartes",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 2,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "AD",
#         "shortDesc": "AD",
#         "longDesc": "Accidental Death",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 8,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "AMB",
#         "shortDesc": "AMB",
#         "longDesc": "Ambulance Service",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 8,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BABYM",
#         "shortDesc": "BabySeatMX",
#         "longDesc": "Baby Seat MX",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "Y",
#         "allowQty": "Y",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BABYU",
#         "shortDesc": "BabySeatUS",
#         "longDesc": "CHILD SEAT",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "Y",
#         "allowQty": "Y",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BCP00",
#         "shortDesc": "ClPrLs00%",
#         "longDesc": "BuyDwn Coll Part Loss 00%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 18,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BCP02",
#         "shortDesc": "ClPrLs02%",
#         "longDesc": "BuyDwn Col Part Loss 02%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BCP05",
#         "shortDesc": "ClPrLs05%",
#         "longDesc": "BuyDwn Coll Part Loss 05%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BCP10",
#         "shortDesc": "ClPrLs10%",
#         "longDesc": "BuyDwn Coll Part Loss 10%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BCP20",
#         "shortDesc": "ClPrLs20%",
#         "longDesc": "BuyDwn Coll Part Loss 20%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "BCT00",
#         "shortDesc": "ClTtLs00%",
#         "longDesc": "BuyDwn Coll Totl Loss 00%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 16,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#      {
#         "optionCode": "FC03",
#         "shortDesc": "FCover 00%Ttl 00%Ptl",
#         "longDesc": "FCover 00%Ttl 00%Ptl",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "PFC03"
#     },
#     {
#         "optionCode": "FC0%1",
#         "shortDesc": "FCV 00T01P",
#         "longDesc": "Fuel Charge 00%TotLoss 01%PartLoss",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "PFC03"
#     },
#     {
#         "optionCode": "FC0&1",
#         "shortDesc": "FCV 00T01P",
#         "longDesc": "Fuel Charge 00%TotLoss 01%PartLoss",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "PFC03"
#     },
#     {
#         "optionCode": "FC0&5",
#         "shortDesc": "FCV 00T00P",
#         "longDesc": "Fuel Charge 00%TotLoss 05%PartLoss",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "PFC03"
#     },
#     {
#         "optionCode": "FC01",
#         "shortDesc": "FC1 00T10P",
#         "longDesc": "Full Cover 00%TotLoss 10%PartLoss",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "PFC03"
#     },
#     {
#         "optionCode": "FC02",
#         "shortDesc": "FC2 00T05P",
#         "longDesc": "Full Cover 00%TotLoss 05%PartLoss",  
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "PFC03"
#     },
#      {
#         "optionCode": "FPO",
#         "shortDesc": "FUEL PURCH",
#         "longDesc": "Fuel Purchase Option",
#         "typeFlag": "F",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "FUEL",
#         "shortDesc": "FUEL",
#         "longDesc": "Fuel",
#         "typeFlag": "F",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "ITCOM",
#         "shortDesc": "ItVchrCom",
#         "longDesc": "Tour Voucher Commission",
#         "typeFlag": "N",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "KEY",
#         "shortDesc": "Rep Key",
#         "longDesc": "Lost or Replacement Keys",
#         "typeFlag": "M",
#         "glAccount": None,
#         "echo": "Y",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "LDW",
#         "shortDesc": "LDW ColTft",
#         "longDesc": "Loss Damage Waiver",
#         "typeFlag": "L",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "CSADJ",
#         "shortDesc": "ADJUST",
#         "longDesc": "Customer Service Adjustment",
#         "typeFlag": "A",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "CVG2",
#         "shortDesc": "Thft0%",
#         "longDesc": "Theft Protection 0%",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "CVG3",
#         "shortDesc": "PAI",
#         "longDesc": "Personal Accident Insurance",
#         "typeFlag": "C",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "DEL",
#         "shortDesc": "DELIVERY",
#         "longDesc": "Delivery Charge",
#         "typeFlag": "D",
#         "glAccount":None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "DISC",
#         "shortDesc": "DISCOUNT",
#         "longDesc": "Discount",
#         "typeFlag": "X",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "N",
#         "rptAsRev": "N",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "DISFA",
#         "shortDesc": "DiscFreeAm",
#         "longDesc": "Discount Free Amount",
#         "typeFlag": "N",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "DISFP",
#         "shortDesc": "DiscFreePc",
#         "longDesc": "Discount Free Percentage",
#         "typeFlag": "N",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "N",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#     {
#         "optionCode": "MTPL",
#         "shortDesc": "Min TPL",
#         "longDesc": "Minimum Third Party Liability",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": None
#     },
#       {
#         "optionCode": "LOCN",
#         "shortDesc": "",
#         "longDesc": "",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "1"
#     },
#     {
#         "optionCode": "TAX",
#         "shortDesc": "",
#         "longDesc": "",
#         "typeFlag": "T",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "1"
#     },
#     {
#         "optionCode": "LRF",
#         "shortDesc": "",
#         "longDesc": "",
#         "typeFlag": "O",
#         "glAccount": None,
#         "echo": "N",
#         "allowQty": "N",
#         "insOnly": "N",
#         "passThru": "Y",
#         "rptAsRev": "Y",
#         "webResVisible": "Y",
#         "dueReport": 0.0,
#         "duePenalty": 0.0,
#         "expireDate": "2025-12-31",
#         "insInvPysCls": "Cls",
#         "assetByUnit": "Unit",
#         "effBlkRmvTyp": "Type",
#         "startDate": "2024-01-01",
#         "linkedOpt": "Opt",
#         "restEbdsAuthOpt": "Auth",
#         "blk1wyMilesSeq": 1,
#         "modifiedDate": "2024-07-23",
#         "modifiedTime": 10.0,
#         "modifiedEmployee": "Employee",
#         "dayOfWeekPricing": "Pricing",
#         "useGoldOptSetQtyParts": "Parts",
#         "estAsgOptPriAgtRls": "Rls",
#         "optSetCode": "1"
#     },
      
# ]


# # Function to send a POST request
# def send_post_request(url, payload):
#     response = requests.post(url, json=payload)
#     return response.status_code, response.json()

# def main():
#     # Send each request sequentially
#     for payload in requests_payload:
#         status_code, response_json = send_post_request(endpoint_url, payload)
#         print(f'Status Code: {status_code}, Response: {response_json}')

# if __name__ == "__main__":
#     main()
